- title: Editorial Board
  type: time_table
  contents:
    - title: Area Editor
      institution: <a href="https://www.journals.elsevier.com/computer-communications/editorial-board" target="_blank"><font color="#3333FF">Elsevier Computer Communications</font></a>
      year: 2022-
    - title: Associate Editor
      institution: <a href="https://www.journals.elsevier.com/software-impacts/editorial-board" target="_blank"><font color="#3333FF">Elsevier Software Impacts</font></a>
      year: 2021-
    - title: Associate Editor
      institution: <a href="https://ieeexplore.ieee.org/xpl/RecentIssue.jsp?punumber=5971803" target="_blank"><font color="#3333FF">Tsinghua Science and Technology journal</font></a>
      year: 2024-

- title: Board Member
  type: time_table
  contents:
    - title: Vice Chair
      institution: AI/ML Section SIG IEEE Technical Committee on Cognitive Networks
      year: 2023-
    - title: Mentoring Co-Chair
      institution: IEEE ComSoc <a href="https://n2women.comsoc.org/officers/2022-n2women-board/" target="_blank"><font color="#3333FF"> N2Women Board</font></a>
      year: 2022
    - title: Panel Member
      institution: Women in AI and Networking Panel in <a href="https://aiedge.osu.edu/women-ai" target="_blank"><font color="#3333FF"> NSF AI Edge Institute</font></a>
      year: 2022

- title: Organizing Committee
  type: time_table
  contents:
    - title: Unclassified Technical Program Co-Chair
      institution: <font color="#3333FF"><a href="https://milcom2024.ieee-milcom.org" target="_blank"> IEEE Military Communications Conference (MILCOM)</a></font>
      year: 2024
    - title: Publication Chair
      institution: <font color="#3333FF"><a href="https://dyspan2024.ieee-dyspan.org" target="_blank"> IEEE International Symposium on Dynamic Spectrum Access Networks (DySPAN)</a></font>
      year: 2024
    - title: Track Co-chair
      institution: <a href="https://ieee-msn.org/2023/progcom.php" target="_blank"><font color="#3333FF"> IEEE International Conference on Mobility, Sensing and Networking (MSN)</font></a>
      year: 2023
    - title: EDAS Chair
      institution: <a href="https://milcom2023.milcom.org/committees/organizing-committee" target="_blank"><font color="#3333FF"> IEEE Military Communications Conference (MILCOM)</font></a>
      year: 2023
    - title: Publicity Co-chair
      institution: <font color="#3333FF"><a href="https://ccnc2024.ieee-ccnc.org/committees/organizing-committee" target="_blank">IEEE Consumer Communications & Networking Conference (CCNC)</a></font>
      year: 2022-2025
    - title: Web Chair
      institution: <font color="#3333FF"><a href="https://dyspan2021.ieee-dyspan.org" target="_blank">IEEE International Symposium on Dynamic Spectrum Access Networks (DySPAN)</a></font>
      year: 2021
    - title: Online and Poster Co-chair
      institution: <a href="https://lanman2021.ieee-lanman.org/committee/" target="_blank">IEEE International Symposium on Local and Metropolitan Area Networks (LANMAN)</a></font>
      year: 2021
    - title: Session Chair
      institution: <a href="https://infocom2023.ieee-infocom.org" target="_blank">IEEE International Conference on Computer Communications (INFOCOM)</a></font>
      year: 2021-2023

- title: Technical Program Committee
  type: time_table
  contents:
      - year: 2024
        items:
          - In ACM International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing <font color="#3333FF">(ACM MobiHoc)</font>
          - In IEEE Consumer Communications & Networking Conference  <font color="#3333FF">(IEEE CCNC)</font>
          - In 'Mobile and Wireless Networks Symposium'  track at IEEE International Conference on Communications  <font color="#3333FF">(IEEE ICC)</font>
          - In 'Cognitive Radio & AI-Enabled Networks'  track at IEEE International Conference on Communications  <font color="#3333FF">(IEEE ICC)</font>
          - In 'Next Generation Spectrum Sharing Technology' workshop at IEEE International Conference on Communications  <font color="#3333FF">(IEEE ICC)</font>
          - In IEEE IEEE International Symposium on Dynamic Spectrum Access Networks  <font color="#3333FF">(IEEE DySPAN)</font>

      - year: 2023
        items:
          - In ACM International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing <font color="#3333FF">(ACM MobiHoc)</font>
          - In IEEE `Internet of Things and Cyber Physical Systems' at IEEE International Conference on Distributed Computing Systems <font color="#3333FF">(IEEE ICDCS)</font>
          - In IEEE 'Mobile and Wireless Networks Symposium'  track at IEEE International Conference on Communications  <font color="#3333FF">(IEEE ICC)</font>
          - In IEEE Consumer Communications & Networking Conference  <font color="#3333FF">(IEEE CCNC)</font>
          - In IEEE 'Signal Transmission and Reception' track at IEEE 96th Vehicular Technology Conference  <font color="#3333FF">(IEEE VTC) </font>
      - year: 2022
        items:
          - In ACM International Symposium on Theory, Algorithmic Foundations, and Protocol Design for Mobile Networks and Mobile Computing' <font color="#3333FF">(ACM MobiHoc)</font>
          - In IEEE 'Internet of Things and Cyber Physical Systems' at IEEE International Conference on Distributed Computing Systems <font color="#3333FF">(IEEE ICDCS)</font>
          - In IEEE 'Mobile and Wireless Networks Symposium' track at IEEE International Conference on Communications <font color="#3333FF">(IEEE ICC)</font>
          - In IEEE Consumer Communications & Networking Conference  <font color="#3333FF">(IEEE CCNC)</font>
          - In IEEE International Symposium on Local and Metropolitan Area Networks <font color="#3333FF">(IEEE LANMAN)</font>
          - In IEEE 'Green Communications and Networks' track at IEEE 95th Vehicular Technology Conference  <font color="#3333FF">(IEEE VTC) </font>
      - year: 2021
        items:
          - In IEEE International Symposium on Dynamic Spectrum Access Networks  <font color="#3333FF">(IEEE DySPAN) </font>
          - In 'Green Solutions for smArt Environment' workshop <font color="#3333FF">(IEEE ICC)</font>
          - In 'AI/ML in Wireless Sensing, Communication and Applications' track at IEEE Consumer Communications & Networking Conference <font color="#3333FF">(IEEE CCNC)</font>
          - In 'Traffic Congestion in Beyond 5G/6G Networks' (TCB6GN)' workshop, in conjunction with <font color="#3333FF">IEEE CCNC </font>
          - In International Conference on Computer Communications and Networks <font color="#3333FF">(IEEE ICCCN)</font>
          - In 'Serverless To sErvE moRe at Scale' workshop <font color="#3333FF">(ACM CCGrid)</font>

- title: Moderator
  type: time_table
  contents:
    - title: IEEE ComSoc Young Professional Event
      institution: IEEE Consumer Communications & Networking Conference (CCNC)
      year: 2022
      description: <a href= "https://zoom.us/rec/play/2P5sPFfZR_Rrh-t1sQxw4t1cb1WYw8bYcDry_0_PgiQF5WaUBCw2GlJVhL2CdNVriuY4fTpqpCurZGdb.tRpyNjU9Is_Fkwcp?continueMode=true&_x_zm_rtaid=kPWO5mAEQMuBdyo2y7U3zA.1663620856349.c3eee56508ea1bd89ebf396e31382ea4&_x_zm_rhtaid=971" parent = '_blank'> Video link  </a>
        # - title: Description 3.
        #   contents:
        #     - Sub-description 1.
        #     - Sub-description 2.
    - title: Panel on “Women in AI Networking – Industry Career”
      institution: NSF Woman in AI Panel
      year: 2022
      description: <a href= "https://www.youtube.com/watch?v=rRiJEnOiWAU&feature=youtu.be" parent = '_blank'> Video link  </a>

- title: Tutorial
  type: time_table
  contents:
    - title: Practical Use of SDR for Machine Learning in RF Environments
      institution: ACM Southeast Conference (ACMSE)
      year: 2022
      description: <a href= "https://acmse.net/2022/tutorials-offered/#tut-work01" parent = '_blank'> Video link  </a>

- title: Reviewer in Transactions and Journals
  type: nested_list
  contents:
    - title: Transactions
      items:
          - IEEE Journal on Selected Areas in Communications
          - IEEE Transactions on Communications
          - IEEE Transactions on Wireless Communications
          - IEEE Transactions on Networking
          - IEEE Transactions on Mobile Computing
          - IEEE Transactions on Vehicular Technology
          - IEEE Transactions on Information Forensics & Security
          - IEEE Transactions on Cognitive Communications and Networking
          - IEEE Transactions on Intelligent Transportation Systems
    - title: Magazines and Letters
      items:
        - IEEE Internet of Things Magazine
        - IEEE Networks Magazine
        - IEEE Communications Magazine
        - IEEE Communications Letters
        - IEEE Networking Letters
    - title: Journals
      items:
         - Elsevier Pervasive and Mobile Computing
         - Elsevier Computer Communications
         - Elsevier Computational and Structural Biotechnology
